{% set DATA = load_setup_py_data() %}
{% set BRANCH = 'develop' %}

package:
    name: utillib
    version: {{ DATA.get('version')}}

source:
    git_url: https://github.com/jor-/util
    git_rev: {{ BRANCH }}

build:
    number: 0
    noarch: python

requirements:
    build:
        - setuptools >=0.8
        - python
        - numpy
        - scipy >=0.19
        - netcdf4
        - h5py
        - petsc4py
        - cachetools
        - blist
        - colorlog
        - matplotlib
    run:
        - python
        - numpy
        - scipy >=0.19
        - netcdf4
        - h5py
        - petsc4py
        - cachetools
        - blist
        - colorlog
        - matplotlib

about:
    home: {{ DATA.get('url') }}
    summary: {{ DATA.get('description') }}
    license: {{ DATA.get('license') }}
    license_file: LICENSE.txt

extra:
    maintainers:
        - {{ DATA.get('author') }}
